// All GCC shipping services by country with descriptions
export const gccShippingServices = {
  AE: [
    { id: 'aramex', name: 'أرامكس - Aramex', key: 'aramex', description: 'شركة عالمية لخدمات الشحن السريع واللوجستيات والتتبع. تقدم خدمات الشحن الدولي والمحلي وحلول التجارة الإلكترونية' },
    { id: 'dhl', name: 'دي إتش إل - DHL', key: 'dhl', description: 'شبكة شحن عالمية توفر خدمات التوصيل السريع الدولي والمحلي' },
    { id: 'fedex', name: 'فيديكس - FedEx', key: 'fedex', description: 'خدمات شحن دولية موثوقة مع تتبع فوري للشحنات' },
    { id: 'ups', name: 'يو بي إس - UPS', key: 'ups', description: 'حلول لوجستية متكاملة وخدمات شحن سريعة حول العالم' },
    { id: 'empost', name: 'البريد الإماراتي - Emirates Post', key: 'empost', description: 'المشغل الوطني للبريد في دولة الإمارات العربية المتحدة' },
    { id: 'albaraka', name: 'مجموعة البركة - Al Baraka', key: 'albaraka', description: 'خدمات شحن وبنكية متكاملة تابعة لمجموعة البركة، حلول مالية ولوجستية متكاملة في الخليج' },
    { id: 'alfuttaim', name: 'مجموعة الفطيم - Al Futtaim', key: 'alfuttaim', description: 'حلول لوجستية متكاملة تابعة لمجموعة فطيم، تشمل الشحن والتوزيع وخدمات سلسلة الإمداد في المنطقة' },
    { id: 'alshaya', name: 'مجموعة الشايع - Al Shaya', key: 'alshaya', description: 'مجموعة تعمل في الشحن والتوزيع لعلامات تجارية متعددة، وتوفر حلول التوزيع واللوجستيات للتجزئة' },
    { id: 'shipco', name: 'شركة الشحن العالمية - ShipCo', key: 'shipco', description: 'مزود خدمات شحن دولي ومحلي متخصص في الشحن البحري والجوي وحلول الشحن للمستوردين والمصدرين' },
  ],
  SA: [
    { id: 'smsa', name: 'سمسا - SMSA', key: 'smsa', description: 'أكبر شركة شحن سعودية متخصصة في التوصيل السريع والخدمات اللوجستية' },
    { id: 'aramex', name: 'أرامكس - Aramex', key: 'aramex', description: 'شركة عالمية لخدمات الشحن السريع واللوجستيات والتتبع. تقدم خدمات الشحن الدولي والمحلي وحلول التجارة الإلكترونية' },
    { id: 'dhl', name: 'دي إتش إل - DHL', key: 'dhl', description: 'شبكة شحن عالمية توفر خدمات التوصيل السريع الدولي والمحلي' },
    { id: 'zajil', name: 'زاجل - Zajil', key: 'zajil', description: 'شركة سعودية رائدة في خدمات البريد السريع والشحن' },
    { id: 'naqel', name: 'ناقل - Naqel', key: 'naqel', description: 'حلول شحن متطورة وخدمات لوجستية متكاملة داخل المملكة' },
    { id: 'saudipost', name: 'البريد السعودي - Saudi Post', key: 'saudipost', description: 'المشغل الوطني للبريد في المملكة العربية السعودية' },
    { id: 'fedex', name: 'فيديكس - FedEx', key: 'fedex', description: 'خدمات شحن دولية موثوقة مع تتبع فوري للشحنات' },
    { id: 'ups', name: 'يو بي إس - UPS', key: 'ups', description: 'حلول لوجستية متكاملة وخدمات شحن سريعة حول العالم' },
    { id: 'albaraka', name: 'مجموعة البركة - Al Baraka', key: 'albaraka', description: 'خدمات شحن وبنكية متكاملة تابعة لمجموعة البركة، حلول مالية ولوجستية متكاملة في الخليج' },
    { id: 'national', name: 'الشركة الوطنية للشحن - National Shipping', key: 'national', description: 'خدمات شحن وبحرية ولوجستيات شاملة، تغطي الشحن التجاري والبحري وخدمات النقل البحري داخل وخارج المملكة' },
    { id: 'hellmann', name: 'هايلمان العالمية - Hellmann', key: 'hellmann', description: 'شبكة دولية لخدمات الشحن واللوجستيات، تقدم خدمات الشحن الدولي والنقل البري والبحري والجوي' },
    { id: 'dsv', name: 'دي إس في - DSV', key: 'dsv', description: 'حلول شحن ولوجستيات متطورة تشمل الشحن الجوي، البحري، والنقل البري بالإضافة إلى تخزين وإدارة سلسلة الإمداد' },
    { id: 'agility', name: 'مجموعة الجاهلية - Agility', key: 'agility', description: 'خدمات لوجستية وشحن متطورة وحلول سلسلة إمداد واسعة النطاق في المنطقة والعالم' },
  ],
  KW: [
    { id: 'kwpost', name: 'البريد الكويتي - Kuwait Post', key: 'kwpost', description: 'المشغل الوطني للبريد في دولة الكويت' },
    { id: 'dhlkw', name: 'دي إتش إل - DHL', key: 'dhlkw', description: 'شبكة شحن عالمية توفر خدمات التوصيل السريع الدولي والمحلي' },
    { id: 'aramex', name: 'أرامكس - Aramex', key: 'aramex', description: 'شركة عالمية لخدمات الشحن السريع واللوجستيات والتتبع. تقدم خدمات الشحن الدولي والمحلي وحلول التجارة الإلكترونية' },
    { id: 'fedex', name: 'فيديكس - FedEx', key: 'fedex', description: 'خدمات شحن دولية موثوقة مع تتبع فوري للشحنات' },
    { id: 'ups', name: 'يو بي إس - UPS', key: 'ups', description: 'حلول لوجستية متكاملة وخدمات شحن سريعة حول العالم' },
    { id: 'albaraka', name: 'مجموعة البركة - Al Baraka', key: 'albaraka', description: 'خدمات شحن وبنكية متكاملة تابعة لمجموعة البركة، حلول مالية ولوجستية متكاملة في الخليج' },
    { id: 'shipco', name: 'شركة الشحن العالمية - ShipCo', key: 'shipco', description: 'مزود خدمات شحن دولي ومحلي متخصص في الشحن البحري والجوي وحلول الشحن للمستوردين والمصدرين' },
    { id: 'agility', name: 'مجموعة الجاهلية - Agility', key: 'agility', description: 'خدمات لوجستية وشحن متطورة وحلول سلسلة إمداد واسعة النطاق في المنطقة والعالم' },
  ],
  QA: [
    { id: 'qpost', name: 'البريد القطري - Qatar Post', key: 'qpost', description: 'المشغل الوطني للبريد في دولة قطر' },
    { id: 'dhlqa', name: 'دي إتش إل - DHL', key: 'dhlqa', description: 'شبكة شحن عالمية توفر خدمات التوصيل السريع الدولي والمحلي' },
    { id: 'aramex', name: 'أرامكس - Aramex', key: 'aramex', description: 'شركة عالمية لخدمات الشحن السريع واللوجستيات والتتبع. تقدم خدمات الشحن الدولي والمحلي وحلول التجارة الإلكترونية' },
    { id: 'fedex', name: 'فيديكس - FedEx', key: 'fedex', description: 'خدمات شحن دولية موثوقة مع تتبع فوري للشحنات' },
    { id: 'ups', name: 'يو بي إس - UPS', key: 'ups', description: 'حلول لوجستية متكاملة وخدمات شحن سريعة حول العالم' },
    { id: 'albaraka', name: 'مجموعة البركة - Al Baraka', key: 'albaraka', description: 'خدمات شحن وبنكية متكاملة تابعة لمجموعة البركة، حلول مالية ولوجستية متكاملة في الخليج' },
    { id: 'alfuttaim', name: 'مجموعة الفطيم - Al Futtaim', key: 'alfuttaim', description: 'حلول لوجستية متكاملة تابعة لمجموعة فطيم، تشمل الشحن والتوزيع وخدمات سلسلة الإمداد في المنطقة' },
    { id: 'hellmann', name: 'هايلمان العالمية - Hellmann', key: 'hellmann', description: 'شبكة دولية لخدمات الشحن واللوجستيات، تقدم خدمات الشحن الدولي والنقل البري والبحري والجوي' },
  ],
  OM: [
    { id: 'omanpost', name: 'البريد العُماني - Oman Post', key: 'omanpost', description: 'المشغل الوطني للبريد في سلطنة عُمان' },
    { id: 'dhlom', name: 'دي إتش إل - DHL', key: 'dhlom', description: 'شبكة شحن عالمية توفر خدمات التوصيل السريع الدولي والمحلي' },
    { id: 'aramex', name: 'أرامكس - Aramex', key: 'aramex', description: 'شركة عالمية لخدمات الشحن السريع واللوجستيات والتتبع. تقدم خدمات الشحن الدولي والمحلي وحلول التجارة الإلكترونية' },
    { id: 'fedex', name: 'فيديكس - FedEx', key: 'fedex', description: 'خدمات شحن دولية موثوقة مع تتبع فوري للشحنات' },
    { id: 'ups', name: 'يو بي إس - UPS', key: 'ups', description: 'حلول لوجستية متكاملة وخدمات شحن سريعة حول العالم' },
    { id: 'jinaken', name: 'جيناكم للتوصيل - Genacom', key: 'jinaken', description: 'شركة توصيل عُمانية محلية تقدم خدمات التوصيل والشحن داخل سلطنة عُمان مع شبكة فروع واسعة وخدمة تتبع' },
    { id: 'albaraka', name: 'مجموعة البركة - Al Baraka', key: 'albaraka', description: 'خدمات شحن وبنكية متكاملة تابعة لمجموعة البركة، حلول مالية ولوجستية متكاملة في الخليج' },
    { id: 'national', name: 'الشركة الوطنية للشحن - National Shipping', key: 'national', description: 'خدمات شحن وبحرية ولوجستيات شاملة، تغطي الشحن التجاري والبحري وخدمات النقل البحري داخل وخارج المملكة' },
    { id: 'dsv', name: 'دي إس في - DSV', key: 'dsv', description: 'حلول شحن ولوجستيات متطورة تشمل الشحن الجوي، البحري، والنقل البري بالإضافة إلى تخزين وإدارة سلسلة الإمداد' },
    { id: 'shipco', name: 'شركة الشحن العالمية - ShipCo', key: 'shipco', description: 'مزود خدمات شحن دولي ومحلي متخصص في الشحن البحري والجوي وحلول الشحن للمستوردين والمصدرين' },
  ],
  BH: [
    { id: 'bahpost', name: 'البريد البحريني - Bahrain Post', key: 'bahpost', description: 'المشغل الوطني للبريد في مملكة البحرين' },
    { id: 'dhlbh', name: 'دي إتش إل - DHL', key: 'dhlbh', description: 'شبكة شحن عالمية توفر خدمات التوصيل السريع الدولي والمحلي' },
    { id: 'aramex', name: 'أرامكس - Aramex', key: 'aramex', description: 'شركة عالمية لخدمات الشحن السريع واللوجستيات والتتبع. تقدم خدمات الشحن الدولي والمحلي وحلول التجارة الإلكترونية' },
    { id: 'fedex', name: 'فيديكس - FedEx', key: 'fedex', description: 'خدمات شحن دولية موثوقة مع تتبع فوري للشحنات' },
    { id: 'ups', name: 'يو بي إس - UPS', key: 'ups', description: 'حلول لوجستية متكاملة وخدمات شحن سريعة حول العالم' },
    { id: 'albaraka', name: 'مجموعة البركة - Al Baraka', key: 'albaraka', description: 'خدمات شحن وبنكية متكاملة تابعة لمجموعة البركة، حلول مالية ولوجستية متكاملة في الخليج' },
    { id: 'alshaya', name: 'مجموعة الشايع - Al Shaya', key: 'alshaya', description: 'مجموعة تعمل في الشحن والتوزيع لعلامات تجارية متعددة، وتوفر حلول التوزيع واللوجستيات للتجزئة' },
    { id: 'hellmann', name: 'هايلمان العالمية - Hellmann', key: 'hellmann', description: 'شبكة دولية لخدمات الشحن واللوجستيات، تقدم خدمات الشحن الدولي والنقل البري والبحري والجوي' },
  ],
};

export const getServicesByCountry = (countryCode: string) => {
  return gccShippingServices[countryCode as keyof typeof gccShippingServices] || [];
};
